name: '🐞 Bug report'
description: 'Report an issue or possible bug'
labels: ['bug']

body:
  - type: input
    id: bug-url
    attributes:
      label: Bug URL
      description: URL where the bug occurred
      placeholder: https://example.com

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: Steps to reproduce the behavior...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior here...
    validations:
      required: true

  - type: checkboxes
    id: system-info
    attributes:
      label: System Information
      description: Please check the information you can provide.
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: iOS
        - label: Android

  - type: checkboxes
    id: browser-info
    attributes:
      label: Browser Information
      description: Please check the information you can provide.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: Internet Explorer

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add additional context here...
